/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tonmoy
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class Booking extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        Table();
    }
    public void Table(){
        conn=MysqlConnect.ConnectionDB();
        try{
            pst=conn.prepareStatement("select source,destination,amount from aupdate");
            rs=pst.executeQuery();
            if(rs.next())
            {
                rs=pst.executeQuery();
                 jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }else{
                JOptionPane.showMessageDialog(null, "Invalid");
            }
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(713, 101, 452, 402);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Flight Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(711, 69, 117, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("SSN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(286, 311, 36, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(269, 359, 53, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("From");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(276, 122, 46, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("To");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 70, 22, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(279, 255, 43, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Seat no");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(254, 500, 68, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Amount");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(251, 642, 71, 22);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(365, 309, 177, 32);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(365, 359, 177, 29);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(365, 255, 177, 28);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(365, 500, 177, 28);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(365, 635, 177, 29);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Jessore", "Ctg" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(365, 69, 177, 28);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Jessore", "Ctg" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(365, 121, 177, 31);

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 640, 90, 40);

        jButton2.setText("show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 550, 90, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Flight ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(244, 29, 78, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(365, 21, 177, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Mobile Number");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(185, 417, 137, 22);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(370, 410, 177, 31);

        jButton3.setText("search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(601, 25, 80, 50);

        jLabel11.setText("departure time");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(251, 185, 71, 14);

        jLabel12.setText("Arival time");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(272, 220, 50, 14);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(365, 170, 177, 29);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(365, 217, 177, 30);

        jLabel13.setText("Total seat");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(274, 472, 48, 14);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(365, 459, 167, 30);

        jLabel14.setText("Available seat");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(255, 573, 67, 14);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(365, 560, 177, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        conn=MysqlConnect.ConnectionDB();
        String source=(String)jComboBox1.getSelectedItem();
        String destination=(String)jComboBox2.getSelectedItem();
        String a1=jTextField6.getText();
        String total=jTextField10.getText();
        /*try
        {
            pst=conn.prepareStatement("select * from aupdate where fid=?");
            pst.setString(1, total);
            //rs.
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }*/
        
        try
        {
            pst=conn.prepareStatement("select * from aupdate where source=? and destination=?");
            pst.setString(1, source);
            pst.setString(2, destination);
            
            rs=pst.executeQuery();
            if(rs.next())
            {
                String a2=rs.getString("amount");
                int sum=Integer.parseInt(a1)*Integer.parseInt(a2);
                String sum1=String.valueOf(sum);
                jTextField7.setText(sum1);
                
                String a3=rs.getString("snumber");
                int minus=Integer.parseInt(total) - Integer.parseInt(a1);
                String minus1=String.valueOf(minus);
                jTextField11.setText(minus1);
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        String fid=jTextField3.getText();
        try
        {
            String val1=jTextField11.getText();
            pst=conn.prepareStatement("update aupdate set aseat='"+val1+"' where fid='"+fid+"'");
              pst.execute();        
        }catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        conn=MysqlConnect.ConnectionDB();
        
        String fid=jTextField3.getText();
        String source=(String)jComboBox1.getSelectedItem();
        String destination=(String)jComboBox2.getSelectedItem();
        String date=jTextField5.getText();
        String ssn=jTextField1.getText();
        String name=jTextField2.getText();
        String mobile=jTextField4.getText();
        String seat=jTextField6.getText();
        String amount=jTextField7.getText();
        String departure=jTextField8.getText();
        String arival=jTextField9.getText();
        
        try
        {
            pst=conn.prepareStatement("insert into local_info values(?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, fid);
            pst.setString(2, source);
            pst.setString(3, destination);
            pst.setString(4, date);
            pst.setString(5, ssn);
            pst.setString(6, name);
            pst.setString(7, mobile);
            pst.setString(8, seat);
            pst.setString(9, amount);
            pst.setString(10, departure);
            pst.setString(11, arival);
            int i=pst.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(null, "Data is Sumbitted");
            }
            else{
                JOptionPane.showMessageDialog(null, "Data is not Sumbitted");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        conn=MysqlConnect.ConnectionDB();
        String fid=jTextField3.getText();
        try
        {
            pst=conn.prepareStatement("select * from aupdate where fid=?");
            pst.setString(1, fid);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("atime");
                jTextField8.setText(add1);
                String add2=rs.getString("dtime");
                jTextField9.setText(add2);
                String add3=rs.getString("aseat");
                jTextField10.setText(add3);
                String add4=rs.getString("day");
                jTextField5.setText(add4);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
